### ISSUE TITLE
9. Adding Notes

### ISSUE THREAD

**Issue by kajunspice** [MakeSchool-Tutorials/MakeSchoolNotes-Swift3-V2#1]
In the section on Saving the Note, the instructions mention lines 1 2 and 3 but there are only two added lines specified in the code block (and described after)

Add the lines marked 1 2 and 3 to the prepare(for:sender:) method in the Display Note View Controller class:
override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    if let identifier = segue.identifier {
        if identifier == "Cancel" {
            print("Cancel button tapped")
        } else if identifier == "Save" {
            print("Save button tapped")

            let note = Note()
            note.title = noteTitleTextField.text ?? ""
            note.content = noteContentTextView.text
            note.modificationTime = Date()

            // 1
            let listNotesTableViewController = segue.destination as! ListNotesTableViewController
            // 2
            listNotesTableViewController.notes.append(note)
        }
    }
}

**Comment by dionlarson** [comment]
This is just a typo. Thank you for bringing it to our attention!
