### ISSUE TITLE
7. Introduction to Bar Button Items

### ISSUE THREAD

**Issue by jaramirez1729** [MakeSchool-Tutorials/MakeSchoolNotes-Swift3-V2#10]
I noticed that the segues to the view controller are camel case (displayNote, addNote) but I then noticed that the exit segues are not camel case (Cancel, Save). This isn't a big deal but breaks consistency and students might ask why we capitalize one over the other. As far as I've been reading around, segues should be camel case just to stick to Swift's naming conventions.

**Comment by dionlarson** [comment]
Fixed.
