### ISSUE TITLE
15. Congratulations!

### ISSUE THREAD

**Issue by jaramirez1729** [MakeSchool-Tutorials/MakeSchoolNotes-Swift3-V2#11]
having completed the app, I might've missed it,  but I didn't see a fix for this issue:

`cell.noteModificationTimeLabel.text = note.modificationTime.convertToString()`

I've seen the other issues that addressed this and I also have the extension that was added to take into account that Core Data uses NSDate, but I still didn't see whether we should actually change this line of code into force unwrapping modificationTime or use optional chaining.

As I remember, originally there was no error at all, only until Core Data was added did the error show up. I originally didn't get any error as the course states that there would be an error.

**Comment by dionlarson** [comment]
Fixed
