### ISSUE TITLE
Notes App - Screenshots misleading

### ISSUE THREAD

**Issue by tlambrou** [MakeSchool-Tutorials/MakeSchoolNotes-Swift3-V2#15]
Screenshots on "5. Creating View Controllers" have the segue and nav bar already added.  https://www.makeschool.com/academy/tutorial/build-a-notes-app-with-coredata/creating-view-controllers-12e78630-6e29-447f-a2cc-160bff2d37b6

**Comment by dionlarson** [comment]
Fixed.
