### ISSUE TITLE
1. Welcome to Make School Notes!

### ISSUE THREAD

**Issue by trevinwisaksana** [MakeSchool-Tutorials/MakeSchoolNotes-Swift3-V2#33]
Please add the Github repo of the completed project. It seems that this hasn't been completed as it's left as a TODO as shown in the screenshot.

<img width="692" alt="todo" src="https://user-images.githubusercontent.com/20000813/34371345-49be15ac-eb07-11e7-948b-541520bf3f60.png">

**Comment by dionlarson** [comment]
Fixed
