### ISSUE TITLE
2. Introduction to Table Views

### ISSUE THREAD

**Issue by pounda** [MakeSchool-Tutorials/MakeSchoolNotes-Swift3-V2#34]
The videos don't seem to be showing the tutorial. Please could you take a look?

Thanks
Tony

**Comment by dionlarson** [comment]
Fixed in https://github.com/MakeSchool-Tutorials/MakeSchoolNotes-Swift3-V2/commit/06ed3e806f4b6022deaa1a12facfd5d6212c0a47
