### ISSUE TITLE
14. Integrating CoreData

### ISSUE THREAD

**Issue by chuckySF** [MakeSchool-Tutorials/MakeSchoolNotes-Swift3-V2#6]
It looks like CoreData stores date as NSDate and not Date as the code is expecting, therefore it will crash when trying to perform "convertToString()" on NSDate. 

Suggesting adding an additional note to modify this line of code to prevent the crash. In ListNotesTableViewController.swift, under tableView cellForRowAt change:

        cell.noteModificationTimeLabel.text = note.modificationTime.convertToString()

to:

        cell.noteModificationTimeLabel.text  = (note.modificationTime! as Date).convertToString()

**Comment by dionlarson** [comment]
Decided to add this to the starter:

```
extension NSDate {
    func convertToString() -> String {
        return DateFormatter.localizedString(from: (self as Date), dateStyle: DateFormatter.Style.medium, timeStyle: DateFormatter.Style.medium)
    }
}
```
