### ISSUE TITLE
First video doesn't load

### ISSUE THREAD

**Issue by danieljku** [MakeSchool-Tutorials/MakeSchoolNotes-Swift3-V2#7]
The very first video that should show how the final app should look never loads for me. Hopefully its just my computer.

**Comment by dionlarson** [comment]
I seem to be having an issues as well. Do the other videos work fine? This one downloads fine...

**Comment by dionlarson** [comment]
None of them on this tutorial work for me. Will wait until tomorrow to see if it's just an S3 issue.

**Comment by tlambrou** [comment]
Most videos not showing for me on this tutorial

**Comment by dionlarson** [comment]
Fixed. Apparently `.mov` does not play well with browsers now, converted to `.mp4`.
