### ISSUE TITLE
5. Creating View Controllers

### ISSUE THREAD

**Issue by jaramirez1729** [MakeSchool-Tutorials/MakeSchoolNotes-Swift3-V2#9]
The order of the screenshots might seem misleading and made me think that I had missed a step. 

- The first screenshot in the "Displaying and Editing Text" section, the table we just added has a navigation bar embed in it. The next screenshot where we add auto layouts, the image does not have the navigation bar.

- In the next section "Running the App!," the screenshot then shows a navigation bar added again. And then when running the app, the screenshot does not have a navigation bar in it.

At first I thought I missed a step in adding the navigation bar to the new view controller, but it doesn't seem like we have done so yet. So I think it seems a bit odd that there is a screenshot where the navigation bar is in it, then it's not, then it's in it again, then it is not. Students might think they also missed a step when they didn't.

**Comment by dionlarson** [comment]
Fixed.
